default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: back_development

test:
  <<: *default
  database: back_test

production:
  <<: *default
  database: back_production
  username: back
  password: <%= ENV["BACK_DATABASE_PASSWORD"] %>
